<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBue77SD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBue77SD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBue77SD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBue77SD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBue77SD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Bue77SD',
    'container.build_id' => '6a26b7bc',
    'container.build_time' => 1674031025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBue77SD');
