<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKZtr8ex\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKZtr8ex/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKZtr8ex.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKZtr8ex\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKZtr8ex\App_KernelDevDebugContainer([
    'container.build_hash' => 'KZtr8ex',
    'container.build_id' => 'fb8e33bb',
    'container.build_time' => 1669208181,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKZtr8ex');
